###########mysql配置#################
mysql:
  username: root
  password: root
  ip: localhost
  port: 3306
  dbname: zoj
##########redis配置##################
redis:
  host: localhost
  port: 6379
  database: 0
  password: root
##########微信公众平台配置################
#wx:
#  callback: callbackUrl
#  appId: appId
#  secret: secret
#  token: token
#  aesKey: aesKey
###########minio配置#####################
#todo:开启minio时取消注释
#oss:
#  enabled: true #是否开启
#  type: minio #oss的类型
#  endpoint: url #minio访问的链接
#  access-key: access-key #accesss-key
#  secret-key: secret-key #secret-key
#  bucketName: name #bucketName

###########swagger配置信息##############
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

knife4j:
  enable: true
  setting:
    language: zh_cn

